### ISSUE TITLE
Issue run optimize

### ISSUE THREAD

**Issue by Prossi79** [notadamking/Bitcoin-Trader-RL#34] opened 2019-06-11 20:16 UTC
Hello! I installed all requirements on my Ubuntu machine, got no error message.  But cannot run optimize.

Following message:

`(Bitcoin-Trader-RL) (base) root@vmanager6003:~/Bitcoin-Trader-RL# python ./optimize.py
Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./optimize.py", line 16, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/__init__.py", line 1, in <module>
    from stable_baselines.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 6, in <module>
    import tensorflow as tf
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
`

**Comment by dumbly91** [comment] 2019-06-12 00:05
you need to update your cuda library version. If you have conda just:

```
conda install cudatoolkit
conda install cudnn
conda install tensorflow-gpu
```

**Comment by rshtirmer** [comment] 2019-06-12 00:13
It's also possible he has no gpu, and should then run:
```conda install tensorflow```

**Comment by Prossi79** [comment] 2019-06-12 07:43
okay, I have installed all above mentioned packages successfully, but still get an error message:

> (base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# python ./optimize.py
Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./optimize.py", line 16, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/__init__.py", line 1, in <module>
    from stable_baselines.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 6, in <module>
    import tensorflow as tf
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

>

**Comment by TalhaAsmal** [comment] 2019-06-12 19:19
@Prossi79 Are you using an anaconda environment, or a standalone python installation?

Also, can you initialize a basic python shell with tensorflow? What is the output of the following:

    import tensorflow as tf
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

**Comment by Prossi79** [comment] 2019-06-13 08:55
I guess I am using an anaconda environment. Opened a python shell and tried to run tensorflow ... got same message as above:


(base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# python
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by lpautet** [comment] 2019-06-13 12:08
Have you tried downgrading to tensor flow 1.12 which need Cuda 9 instead of Cuda 10?

That worked for me at least.

**Comment by TalhaAsmal** [comment] 2019-06-13 12:53
What version of CUDA did you install? It looks like you're missing CUDA 10.0, which can be obtained from https://developer.nvidia.com/cuda-10.0-download-archive

**Comment by Prossi79** [comment] 2019-06-13 13:27
Thanks for reply guys!

1st -> how can I install CUDA? I was thinking its is done by 'conda install cudnn'

2nd -> how could i downgrade tensor flow to  1.12 and install CUDA9?

**Comment by TalhaAsmal** [comment] 2019-06-13 14:06
If you use the following, it seems like it should install all dependencies:

   conda install tensorflow-gpu

If this doesn't work for you, your VPS might not have a GPU.

**Comment by Prossi79** [comment] 2019-06-13 14:31
okay, I have tried to install all again .. cudatoolkit, cudnn and tensorflow (no gpu) - all successfully:

`(Bitcoin-Trader-RL) (base) root@vmanager6003:~/Bitcoin-Trader-RL# conda install tensorflow
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# conda install cudatoolkit
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# conda install cudnn
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

(base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# 
`

**Comment by Prossi79** [comment] 2019-06-13 14:33
I have again executed the requirements -> all good and isntalled .. but still have the error:


(base) (Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL# python ./optimize.py
Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./optimize.py", line 16, in <module>
    from stable_baselines.common.policies import MlpLnLstmPolicy
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/__init__.py", line 1, in <module>
    from stable_baselines.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/__init__.py", line 1, in <module>
    from stable_baselines.a2c.a2c import A2C
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/stable_baselines/a2c/a2c.py", line 6, in <module>
    import tensorflow as tf
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/root/Bitcoin-Trader-RL/Bitcoin-Trader-RL/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Includ

**Comment by TalhaAsmal** [comment] 2019-06-13 19:53
OK, do you have a GPU on your VPS? If not, then there's no need to install any GPU components (CUDA, cuDNN, tensorflow-gpu, TensorRT).

If you don't have a GPU, I suggest starting with a clean virtual environment in conda, and install only tensorflow.

If you DO have a GPU, then make sure to install tensorflow-gpu instead of tensorflow.

**Comment by Prossi79** [comment] 2019-06-14 06:36
stupid beginner questions : ) 

1.) how can I check that my VPS does have a GPU?

2.) how can I remove / delete the env I have created for this bot?

**Comment by TalhaAsmal** [comment] 2019-06-14 16:37
> 1.) how can I check that my VPS does have a GPU?

From the CUDA installation guide (https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html):

> To verify that your GPU is CUDA-capable, go to your distribution's equivalent of System Properties, or, from the command line, enter:
> 
> $ lspci | grep -i nvidia
> If you do not see any settings, update the PCI hardware database that Linux maintains by entering update-pciids (generally found in /sbin) at the command line and rerun the previous lspci command.
> 
> If your graphics card is from NVIDIA and it is listed in http://developer.nvidia.com/cuda-gpus, your GPU is CUDA-capable.

 > 2.) how can I remove / delete the env I have created for this bot?

Execute the following, replacing <environmentName> with the name of your environment:

    conda env remove --name <environmentName>

To list the conda environments:

    conda info --envs

See https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment for more information

**Comment by archenroot** [comment] 2019-06-15 13:36
@Prossi79 - don't get me wrong, but first use google or other search engine and learn about your VPS, if you ask how to check your VPS has GPU it seems like you have no idea what you are actually doing (not just struggling) :-))) 

Anyway the message is quite clear its missing cublas lib compatible with cuda 10, can be caused by your OS version as well probably (I use virtualenv, not conda, so won't help on this), but there are some common rules regarding tensorflow:
`Official tensorflow-gpu binaries (the one downloaded by pip or conda) are built with cuda 9.0, cudnn 7 since TF 1.5, and cuda 10.0, cudnn 7 since TF 1.13`

**Comment by Prossi79** [comment] 2019-06-17 08:07
@archenroot  ... of course I did use Google, but was lost - thank you guys to give some direction and to help how to read the error message. That's the purpose of  this communication isnt it?

Just tried lspci -vkk | grep VGA  in my Ubuntu terminal .. following result:

`(base) root@vmanager6003:~# sudo lspci -vkk | grep VGA
(base) root@vmanager6003:~# 
`
I still cannot see any output like your list ... where is my mistake?

**Comment by archenroot** [comment] 2019-06-17 08:34
@Prossi79 - I suspect you have vps without GPU card assigned to it. What cloud instance do you use and on which cloud provider?

I have my own GPU workstation available, but when I do I use for example Google cloud it works without issues...

**Comment by Prossi79** [comment] 2019-06-17 14:19
I got a German VPS provider https://www.ip-projects.com/products/linux-virtual-server/

I am going to check quickly with them if the have a GPU running

**Comment by notadamking** [comment] 2019-06-21 23:47
This seems to be a problem with the environment, not the codebase, so I am closing this issue.

**Closed by notadamking** 2019-06-21 23:47 UTC
